name: setup-env
description: Setup Environment

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Print .NET version and SDKs
      shell: bash
      run: |
        dotnet --version
        dotnet --list-sdks

    - name: Install WASM tools workload
      shell: bash
      run: dotnet workload install wasm-tools